openapi: 3.0.3
info:
  title: 'Virta API'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/companies:
    get:
      summary: ''
      operationId: getApiV1Companies
      description: ''
      parameters: []
      responses:
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Server error'
                  code: 0
                  error_message: 'Target [App\Modules\Company\Contracts\CompanyRepositoryInterface] is not instantiable while building [Knuckles\Scribe\Commands\GenerateDocumentation, App\Modules\Company\Controllers\Api\V1\CompanyController, App\Modules\Company\Services\CompanyUpdater].'
                properties:
                  message:
                    type: string
                    example: 'Server error'
                  code:
                    type: integer
                    example: 0
                  error_message:
                    type: string
                    example: 'Target [App\Modules\Company\Contracts\CompanyRepositoryInterface] is not instantiable while building [Knuckles\Scribe\Commands\GenerateDocumentation, App\Modules\Company\Controllers\Api\V1\CompanyController, App\Modules\Company\Services\CompanyUpdater].'
      tags:
        - Companies
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  description: ''
                  example: 2
      security: []
    post:
      summary: ''
      operationId: postApiV1Companies
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Companies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: odio
                parent_company_id:
                  type: integer
                  description: ''
                  example: 8
              required:
                - name
      security: []
  '/api/v1/companies/{company}':
    get:
      summary: ''
      operationId: getApiV1CompaniesCompany
      description: ''
      parameters: []
      responses:
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Server error'
                  code: 0
                  error_message: 'Target [App\Modules\Company\Contracts\CompanyRepositoryInterface] is not instantiable while building [Knuckles\Scribe\Commands\GenerateDocumentation, App\Modules\Company\Controllers\Api\V1\CompanyController, App\Modules\Company\Services\CompanyUpdater].'
                properties:
                  message:
                    type: string
                    example: 'Server error'
                  code:
                    type: integer
                    example: 0
                  error_message:
                    type: string
                    example: 'Target [App\Modules\Company\Contracts\CompanyRepositoryInterface] is not instantiable while building [Knuckles\Scribe\Commands\GenerateDocumentation, App\Modules\Company\Controllers\Api\V1\CompanyController, App\Modules\Company\Services\CompanyUpdater].'
      tags:
        - Companies
      security: []
    put:
      summary: ''
      operationId: putApiV1CompaniesCompany
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Companies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: ut
                parent_company_id:
                  type: integer
                  description: ''
                  example: 12
              required:
                - name
      security: []
    delete:
      summary: ''
      operationId: deleteApiV1CompaniesCompany
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Companies
      security: []
    parameters:
      -
        in: path
        name: company
        description: 'The ID of the company.'
        example: 19
        required: true
        schema:
          type: integer
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Server error'
                  code: 0
                  error_message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: 'Server error'
                  code:
                    type: integer
                    example: 0
                  error_message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/stations/search:
    post:
      summary: ''
      operationId: postApiV1StationsSearch
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Stations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                latitude:
                  type: number
                  description: 'Must be between -90 and 90.'
                  example: -90
                longitude:
                  type: number
                  description: 'Must be between -180 and 180.'
                  example: -180
                company_id:
                  type: integer
                  description: ''
                  example: 5
                radius:
                  type: integer
                  description: ''
                  example: 1
                page:
                  type: integer
                  description: ''
                  example: 8
              required:
                - latitude
                - longitude
                - company_id
                - radius
      security: []
  /api/v1/stations:
    get:
      summary: ''
      operationId: getApiV1Stations
      description: ''
      parameters: []
      responses:
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Server error'
                  code: 0
                  error_message: 'Target [App\Modules\Station\Contracts\StationRepositoryInterface] is not instantiable while building [Knuckles\Scribe\Commands\GenerateDocumentation, App\Modules\Station\Controllers\Api\V1\StationController, App\Modules\Station\Services\StationUpdater].'
                properties:
                  message:
                    type: string
                    example: 'Server error'
                  code:
                    type: integer
                    example: 0
                  error_message:
                    type: string
                    example: 'Target [App\Modules\Station\Contracts\StationRepositoryInterface] is not instantiable while building [Knuckles\Scribe\Commands\GenerateDocumentation, App\Modules\Station\Controllers\Api\V1\StationController, App\Modules\Station\Services\StationUpdater].'
      tags:
        - Stations
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  description: ''
                  example: 7
      security: []
    post:
      summary: ''
      operationId: postApiV1Stations
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Stations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: et
                latitude:
                  type: number
                  description: 'Must be between -90 and 90.'
                  example: -89
                longitude:
                  type: number
                  description: 'Must be between -180 and 180.'
                  example: -179
                company_id:
                  type: integer
                  description: ''
                  example: 10
                address:
                  type: string
                  description: ''
                  example: non
              required:
                - name
                - latitude
                - longitude
                - company_id
                - address
      security: []
  '/api/v1/stations/{station}':
    get:
      summary: ''
      operationId: getApiV1StationsStation
      description: ''
      parameters: []
      responses:
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Server error'
                  code: 0
                  error_message: 'Target [App\Modules\Station\Contracts\StationRepositoryInterface] is not instantiable while building [Knuckles\Scribe\Commands\GenerateDocumentation, App\Modules\Station\Controllers\Api\V1\StationController, App\Modules\Station\Services\StationUpdater].'
                properties:
                  message:
                    type: string
                    example: 'Server error'
                  code:
                    type: integer
                    example: 0
                  error_message:
                    type: string
                    example: 'Target [App\Modules\Station\Contracts\StationRepositoryInterface] is not instantiable while building [Knuckles\Scribe\Commands\GenerateDocumentation, App\Modules\Station\Controllers\Api\V1\StationController, App\Modules\Station\Services\StationUpdater].'
      tags:
        - Stations
      security: []
    put:
      summary: ''
      operationId: putApiV1StationsStation
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Stations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: reiciendis
                latitude:
                  type: number
                  description: 'Must be between -90 and 90.'
                  example: -90
                longitude:
                  type: number
                  description: 'Must be between -180 and 180.'
                  example: -180
                company_id:
                  type: integer
                  description: ''
                  example: 14
                address:
                  type: string
                  description: ''
                  example: eligendi
                station:
                  type: integer
                  description: ''
                  example: 19
              required:
                - name
                - latitude
                - longitude
                - company_id
                - address
                - station
      security: []
    delete:
      summary: ''
      operationId: deleteApiV1StationsStation
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Stations
      security: []
    parameters:
      -
        in: path
        name: station
        description: 'The ID of the station.'
        example: 17
        required: true
        schema:
          type: integer
tags:
  -
    name: Companies
    description: ''
  -
    name: Endpoints
    description: ''
  -
    name: Stations
    description: ''
